# Generated by Django 5.0.7 on 2024-12-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_handdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
