# Generated by Django 5.0.4 on 2024-05-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='manager_fk',
            new_name='manager_pro_fk',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='manager_fk',
            new_name='manager_sen_fk',
        ),
    ]
