# Generated by Django 5.0.4 on 2024-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_rename_manager_fk_production_manager_pro_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
