# Generated by Django 5.0.4 on 2024-05-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_alter_sensor_data_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sensor',
        ),
    ]
