# Generated by Django 5.0.4 on 2024-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_delete_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dust', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
