# Generated by Django 5.0.4 on 2024-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='Month_production',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='day_defects',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='day_production',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='dust',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
