# Generated by Django 5.0.4 on 2024-05-13 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_alter_production_month_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
