# Generated by Django 5.0.4 on 2024-05-13 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_production_date_sensor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
