# Generated by Django 5.0.4 on 2024-05-21 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0012_alter_production_date_alter_sensor_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ovensensor',
            fields=[
                ('oven_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
