# Generated by Django 5.0.4 on 2024-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0013_ovensensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='dust',
            new_name='finedust',
        ),
        migrations.AddField(
            model_name='sensor',
            name='ultrafinedust',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
