# Generated by Django 5.0.4 on 2024-05-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0014_rename_dust_sensor_finedust_sensor_ultrafinedust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='finedust',
            new_name='pm10',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='ultrafinedust',
            new_name='pm25',
        ),
    ]
